# Basic Sofle peripheral with DYA sleep/idle settings synchronized from the left.
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_EC11=n
CONFIG_ZMK_POINTING=n
CONFIG_INPUT=y
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
